ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.SerializationKt.configureSerialization
      - com.example.DatabaseKt.configureDatabase
      - com.example.plugins.StatusPagesKt.configureStatusPages
      - com.example.RoutingKt.configureRouting
