ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.prosenjith.todoflow.SerializationKt.configureSerialization
      - com.prosenjith.todoflow.DatabaseKt.configureDatabase
      - com.prosenjith.todoflow.plugins.StatusPagesKt.configureStatusPages
      - com.prosenjith.todoflow.plugins.SecurityKt.configureSecurity
      - com.prosenjith.todoflow.RoutingKt.configureRouting
